### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by svaeni** [tomslominski/yourls-redirect-index#4]
Hi there,

I'm new to github (and no native english speaker) so i hope i don't mess up with too many rules here.

I've downloaded and activated this plugin, however the redirect won't work. I've entered the target url in the format http://www.exampleurl.de. I already tried to deactivate all other plugins. No progress. 

I've put the folder in /user/plugins and copied index.php from there to the root directory of yourls.

Hast anyone any suggestions how to fix this?

Thank you all very much in advance.

**Comment by tomslominski** [comment]
Can you post the URL of your site? Did you enable the plugin in the YOURLS admin panel and set a URL to redirect to on the plugin's page?

**Comment by svaeni** [comment]
the long URL is Arbeitsgerichtsverband.de, the short one is darbgv.de

I use the plugin "Fallback URL" in order to redirect all not used shot-urls to the 404 page of my website. That works finde.

Afterwards I installed "redirect Index", activated it in the admin panel and entered http://www.arbeitsgerichtsverband.de in the plugins config-page. However if you go to darbgv.de you won't be forwarded to Arbeitsgerichtsverband.de.

I also tried to deactivate "fallback URL" to make sure that the problem ist not the parallel usage of both plugins.

**Comment by tomslominski** [comment]
Sorry about my delayed response, GitHub didn't email me when you responded for some reason...

Looking at the source of your page, I think the encoding or something has been messed up. If you look at line 2 here, there's some weird characters instead of ' or ".

![screen shot 2017-05-27 at 10 53 15](https://cloud.githubusercontent.com/assets/739599/26520459/d7cb0caa-42ca-11e7-85c9-34abc08b7519.png)

This code comes from line 17 of index.php, which should look like this https://github.com/tomslominski/yourls-redirect-index/blob/master/index.php#L17 . This could be an issue with either your editor (if you edited this file - you should use a plain text editor like TextEdit or Notepad), your FTP client (passive/active upload modes) or your webserver (something more specific with encoding). Try uploading the index.php file afresh, and if that doesn't help, let me know more about your host/FTP client etc.

**Comment by svaeni** [comment]
Thank you very much!

I've downloaded the user/plugins/redirect-index/index.php directly from the web-interface of 1&1 where this is hosted. 

In looks like this:
![bildschirmfoto 2017-05-27 um 12 08 09](https://cloud.githubusercontent.com/assets/28866641/26520551/493f9dba-42d5-11e7-9d4e-8d230ee15af5.png)

As far as I can tell it looks like it should. I re-uploaded it again using the browser in order to exclude errors from my FTP-client (FileZilla).

Still no progress. 

I then have deactivated the plugin, removed all the files, uploaded them again, activated it, still the same issue, still the same weird characters. Help is very much appreciated.

**Comment by tomslominski** [comment]
ah, I see what's happening. If you go to darbgv.de/index.html (which is what your web server defaults to), you get what you see in my screenshot above. If you go to darbgv.de/index.php, everything works as expected. You need to either remove index.html if you have such a file, or change the default file to index.php (your host will help you with this). Let me know if that's helped!

**Comment by svaeni** [comment]
Deleting the index.html fixed it. Thank you so much for your kind help!

**Comment by tomslominski** [comment]
No worries!
